### PR TITLE
removed most print statements and need for global variables

### PR DESCRIPTION
**Pull request by tasmaniansyrup**

### CODE REVIEW

**Comment by ihalseide** [comment]
When running with my client.py, I get an error that is a problem with the module code:
```
"Battleship.py", line 154, in setupGamePieces
    printGameBoard()
    ^^^^^^^^^^^^^^
NameError: name 'printGameBoard' is not defined. Did you mean: 'personalGameBoard'?
```

Unless I should implement this function myself now and you were leaving this for reference?

**Review by ihalseide — COMMENTED** [review]
yes

**Review by ihalseide — APPROVED** [review]
yes

**Review by Bleple — APPROVED** [review]
seems good

**Pull request merged**
